### ISSUE TITLE
SPI.openSync parameter error

### ISSUE THREAD

**Issue by JimmyPesto** [Jorgen-VikingGod/node-rpi-ws2801#12]
Looking at the docs of spi-device module:
https://github.com/fivdi/spi-device#configuration-options
it says the options parameter of openSync function wants:

> Configuration Options
> [...]
> maxSpeedHz - number, 32-bit, device clock frequency in Hertz, default system specific

Currently this modules is calling (rpi-ws2801 line 52):
`      this.spi = SPI.openSync(this.spiBus, this.spiDevice, {'maxSpeed' : this.maxSpeed});`
which should be changed to:
`      this.spi = SPI.openSync(this.spiBus, this.spiDevice, {'maxSpeedHz' : this.maxSpeed});`

**Comment by Jorgen-VikingGod** [comment]
thx for the fix
