### ISSUE TITLE
(node:2612) [DEP0005] DeprecationWarning: Buffer()  - Warning

### ISSUE THREAD

**Issue by JimmyPesto** [Jorgen-VikingGod/node-rpi-ws2801#14]
Using this module will result in the following warning:
`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

As the warning already says this has to be changed:
```

new Buffer(number) // Deprecated 
Buffer.alloc(number) // New
```
source:
https://stackoverflow.com/questions/57063659/deprecationwarning-buffer-is-deprecated-due-to-security-and-usability-issues

Would you like to get a pull request for this or could you correct it?

**Comment by Jorgen-VikingGod** [comment]
thx for reporting this issue.
